Auth
we-b/PHP_Pictweet pull request #5
Opened 2018-08-15 08:40 UTC by DAIHI

# 実装機能
- ユーザー登録/ログイン機能
- ログイン有無でビュー表示切り替え

2018-08-15 08:44 UTC, rokuyamad requested changes

2018-08-15 08:44 UTC, daikirokuyama commented on resources/views/layout.blade.php
> +            <a href="/logout">ログアウト</a>
ここpostメソッドじゃないとダメなはず

2018-08-16 01:01 UTC, DAIHI commented
ログアウトボタン直しました

2018-08-16 01:07 UTC, rokuyamad reviewed
register.blade.phpかなり変更されますね！
レイアウト結構かわってますよね？

2018-08-16 01:10 UTC, DAIHI commented
変わってました！元のファイルに差し替えました。

2018-08-16 01:12 UTC, rokuyamad approved these changes
LGTM
![LGTM](http://www.lgtm.in/p/kKGNxa1lq)

2018-08-16 01:12 UTC, merged